services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  enricher:
    build: .
    container_name: enricher
    depends_on:
      - elasticsearch
    volumes:
      - ./config.yaml:/app/config.yaml
    env_file:
      - .env
    entrypoint: ["uv", "run", "enricher"]

volumes:
  esdata:
networks:
  gleif_enricher: