services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data
    expose:
      - 9200

  enricher:
    build: .
    container_name: enricher
    depends_on:
      - elasticsearch
    volumes:
      - ./config.yaml:/app/config.yaml
    env_file:
      - .env
    entrypoint: ["poetry", "run", "python", "gleif_enricher/cli.py"]

volumes:
  esdata:
networks:
  gleif_enricher: